[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "https://vercel.com/"
  status = 302

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
